version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: devops-project
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql

  app:
    image: devops-project:1.0
    container_name: springboot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: devops-project
    ports:
      - "8082:8081"
    depends_on:
      - mysql

volumes:
  mysql_data:
